export const REPORT_GROUPS = [
  {
    key: "sales-pos",
    title: "Sales & POS",
    description: "Semua laporan penjualan, transaksi, channel, dan performa menu.",
    reports: [
      {
        key: "sales-recap",
        path: "/erp/reports/sales-recap",
        title: "Sales Recapitulation",
        description: "Ringkasan penjualan utama lintas branch dan channel.",
        purpose: "Halaman ini akan dipakai untuk melihat ringkasan sales lintas branch dalam satu tampilan.",
        ideas: ["Total sales per branch", "Ringkasan harian dan periode", "Breakdown channel online/offline"],
      },
      {
        key: "daily-sales-recap",
        path: "/erp/reports/daily-sales-recap",
        title: "Daily Sales Recapitulation",
        description: "Rekap penjualan harian untuk operasional harian outlet.",
        purpose: "Halaman ini akan dipakai untuk melihat performa penjualan hari ini dan pembanding hari sebelumnya.",
        ideas: ["Sales harian", "Pcs terjual", "Perbandingan day by day"],
      },
      {
        key: "branch-top-sales",
        path: "/erp/reports/branch-top-sales",
        title: "Branch Top Sales",
        description: "Peringkat branch dengan penjualan terbaik.",
        purpose: "Halaman ini akan dipakai untuk membandingkan branch mana yang paling tinggi kontribusi sales-nya.",
        ideas: ["Ranking branch", "Trend sales harian", "Filter periode"],
      },
      {
        key: "sales-by-branch",
        path: "/erp/reports/sales-by-branch",
        title: "Sales by Branch",
        description: "Detail sales per branch.",
        purpose: "Halaman ini akan dipakai untuk melihat detail performa penjualan per branch.",
        ideas: ["Filter branch", "Breakdown sales per periode", "Rekap per outlet"],
      },
      {
        key: "sales-by-cashier",
        path: "/erp/reports/sales-by-cashier",
        title: "Sales by Cashier",
        description: "Kontribusi sales berdasarkan cashier/crew.",
        purpose: "Halaman ini akan dipakai untuk melihat penjualan yang ditangani masing-masing cashier atau crew.",
        ideas: ["Performa per crew", "Total transaksi per cashier", "Sales rupiah dan pcs"],
      },
      {
        key: "sales-by-channel",
        path: "/erp/reports/sales-by-channel",
        title: "Sales by Channel",
        description: "Perbandingan offline dan online.",
        purpose: "Halaman ini akan dipakai untuk membandingkan penjualan offline dan online agar channel mix mudah dipantau.",
        ideas: ["OFFLINE vs ONLINE", "Sales per channel", "Mix transaksi per branch"],
      },
      {
        key: "sales-by-platform",
        path: "/erp/reports/sales-by-platform",
        title: "Sales by Platform",
        description: "Performa GoFood, GrabFood, dan ShopeeFood.",
        purpose: "Halaman ini akan dipakai untuk membandingkan performa tiap platform online per branch atau periode.",
        ideas: ["GoFood / GrabFood / ShopeeFood", "Promo per platform", "Sales per outlet"],
      },
      {
        key: "transaction-detail",
        path: "/erp/reports/transaction-detail",
        title: "Transaction Detail Report",
        description: "Detail transaksi per invoice.",
        purpose: "Halaman ini akan dipakai untuk melihat setiap invoice beserta item, pembayaran, dan branch asal transaksi.",
        ideas: ["Invoice detail", "Item transaksi", "Metode pembayaran"],
      },
      {
        key: "void-transactions",
        path: "/erp/reports/void-transactions",
        title: "Void Transaction Report",
        description: "Daftar transaksi yang dibatalkan.",
        purpose: "Halaman ini akan dipakai untuk memantau transaksi void berikut alasan dan user yang memprosesnya.",
        ideas: ["Daftar void", "Alasan void", "Audit pembatalan transaksi"],
      },
      {
        key: "menu-performance",
        path: "/erp/reports/menu-performance",
        title: "Menu / Product Performance",
        description: "Performa produk berdasarkan qty dan omzet.",
        purpose: "Halaman ini akan dipakai untuk melihat menu apa yang paling laku dan paling besar kontribusi omzet.",
        ideas: ["Top selling menu", "Omzet per menu", "Filter branch dan periode"],
      },
      {
        key: "category-performance",
        path: "/erp/reports/category-performance",
        title: "Category Performance",
        description: "Performa per kategori menu.",
        purpose: "Halaman ini akan dipakai untuk melihat kategori mana yang paling kuat performanya.",
        ideas: ["Kategori terbaik", "Kontribusi sales per kategori", "Perbandingan periode"],
      },
    ],
  },
  {
    key: "cash-settlement",
    title: "Cash & Settlement",
    description: "Laporan kasir, pembayaran, dan rekonsiliasi shift.",
    reports: [
      {
        key: "payment-recap",
        path: "/erp/reports/payment-recap",
        title: "Payment Recapitulation",
        description: "Ringkasan semua metode pembayaran.",
        purpose: "Halaman ini akan dipakai untuk melihat komposisi metode pembayaran yang masuk ke sistem.",
        ideas: ["Cash, QRIS, split", "Online platform payment", "Metode pembayaran per branch"],
      },
      {
        key: "cash-vs-noncash",
        path: "/erp/reports/cash-vs-noncash",
        title: "Cash Sales vs Non-Cash Sales",
        description: "Perbandingan sales cash dan non-cash.",
        purpose: "Halaman ini akan dipakai untuk memisahkan transaksi cash dan non-cash agar kas outlet lebih mudah dikontrol.",
        ideas: ["Cash vs non-cash", "Periode harian/bulanan", "Cross-check outlet cash"],
      },
      {
        key: "cash-sessions",
        path: "/erp/reports/cash-sessions",
        title: "Cash Session Report",
        description: "Data open shift, close shift, dan rekonsiliasi kas.",
        purpose: "Halaman ini akan dipakai untuk memantau sesi kasir, opening cash, expected cash, dan closing cash.",
        ideas: ["Shift aktif dan selesai", "Opening cash", "Expected vs actual cash"],
      },
      {
        key: "opening-cash",
        path: "/erp/reports/opening-cash",
        title: "Opening Cash Report",
        description: "Daftar opening cash per shift.",
        purpose: "Halaman ini akan dipakai untuk melihat modal awal kasir saat shift dibuka.",
        ideas: ["Modal awal", "Opening per branch", "Rekap harian"],
      },
      {
        key: "closing-cash",
        path: "/erp/reports/closing-cash",
        title: "Closing Cash Report",
        description: "Daftar penutupan kas dan hasil akhir shift.",
        purpose: "Halaman ini akan dipakai untuk melihat hasil akhir kas saat shift ditutup.",
        ideas: ["Closing cash", "Hasil akhir shift", "Rekap per crew"],
      },
      {
        key: "expected-cash",
        path: "/erp/reports/expected-cash",
        title: "Expected Cash Report",
        description: "Perkiraan kas berdasarkan transaksi dan expense.",
        purpose: "Halaman ini akan dipakai untuk mencocokkan saldo kas sistem dengan uang fisik di outlet.",
        ideas: ["Expected cash", "Cross-check kas fisik", "Selisih lebih/kurang"],
      },
    ],
  },
  {
    key: "inventory",
    title: "Inventory",
    description: "Stok, opname, movement, dan coverage item per branch.",
    reports: [
      {
        key: "inventory-stock",
        path: "/erp/reports/inventory-stock",
        title: "Inventory Stock Report",
        description: "Stok item per branch.",
        purpose: "Halaman ini akan dipakai untuk melihat stok item yang tersedia di masing-masing branch.",
        ideas: ["Stok per branch", "Min/max stock", "Item wajib opname"],
      },
      {
        key: "stock-opname-opening",
        path: "/erp/reports/stock-opname-opening",
        title: "Stock Opname Opening",
        description: "Opening opname awal shift.",
        purpose: "Halaman ini akan dipakai untuk memantau hasil stock opname pembuka sebelum shift dimulai.",
        ideas: ["Opening opname", "Syarat open shift", "Selisih awal hari"],
      },
      {
        key: "stock-opname-closing",
        path: "/erp/reports/stock-opname-closing",
        title: "Stock Opname Closing",
        description: "Closing opname akhir shift.",
        purpose: "Halaman ini akan dipakai untuk memantau hasil opname penutup saat hari operasional selesai.",
        ideas: ["Closing opname", "Penutup shift", "Ringkasan stok akhir"],
      },
      {
        key: "stock-opname-variance",
        path: "/erp/reports/stock-opname-variance",
        title: "Stock Opname Variance",
        description: "Selisih sistem vs hitungan crew.",
        purpose: "Halaman ini akan dipakai untuk melihat variance antara stok sistem dan stok hasil hitung crew.",
        ideas: ["Variance per item", "Selisih positif/negatif", "Analisis shrinkage"],
      },
      {
        key: "inventory-movement",
        path: "/erp/reports/inventory-movement",
        title: "Inventory Movement",
        description: "Mutasi barang masuk, keluar, dan adjustment.",
        purpose: "Halaman ini akan dipakai untuk audit mutasi stok dari pembelian, penjualan, waste, dan penyesuaian.",
        ideas: ["Barang masuk", "Barang keluar", "Audit movement"],
      },
      {
        key: "branch-product-coverage",
        path: "/erp/reports/branch-product-coverage",
        title: "Branch Product Coverage",
        description: "Cakupan produk yang aktif per branch.",
        purpose: "Halaman ini akan dipakai untuk melihat produk mana saja yang tersedia di outlet tertentu.",
        ideas: ["Produk aktif per branch", "Coverage menu", "Availability outlet"],
      },
    ],
  },
  {
    key: "crew",
    title: "Crew",
    description: "Absensi dan performa crew bulanan.",
    reports: [
      {
        key: "crew-attendance",
        path: "/erp/reports/crew-attendance",
        title: "Crew Attendance Report",
        description: "Rekap kehadiran crew.",
        purpose: "Halaman ini akan dipakai untuk melihat kehadiran crew, open shift, dan close shift per periode.",
        ideas: ["Check-in / check-out", "Absensi per branch", "Rekap harian"],
      },
      {
        key: "crew-monthly-performance",
        path: "/erp/reports/crew-monthly-performance",
        title: "Crew Monthly Performance Report",
        description: "Performa crew per bulan.",
        purpose: "Halaman ini akan dipakai untuk menilai performa crew bulanan berdasarkan sales, pcs, hadir, dan bonus.",
        ideas: ["Kali masuk", "Sales harian", "Estimasi bonus"],
      },
    ],
  },
  {
    key: "expenses",
    title: "Expenses",
    description: "Outlet expense dan pembelian barang operasional.",
    reports: [
      {
        key: "outlet-expense",
        path: "/erp/reports/outlet-expense",
        title: "Outlet Expense Report",
        description: "Rekap expense outlet dan dampaknya ke cash.",
        purpose: "Halaman ini akan dipakai untuk melihat pembelian kecil outlet, nota, dan pengaruhnya ke cash outlet.",
        ideas: ["Expense harian", "Nota pembelian", "Dampak ke cash dan stok"],
      },
    ],
  },
  {
    key: "system",
    title: "Audit & System",
    description: "Jejak aktivitas dan audit perubahan penting.",
    reports: [
      {
        key: "audit-log",
        path: "/erp/reports/audit-log",
        title: "Audit Log Report",
        description: "Catatan perubahan penting di sistem.",
        purpose: "Halaman ini akan dipakai untuk melihat siapa melakukan apa, kapan, dan di branch mana.",
        ideas: ["Log create/update/delete", "Filter user dan branch", "Audit perubahan penting"],
      },
    ],
  },
  {
    key: "finance",
    title: "Finance & AP",
    description: "Laporan keuangan dan hutang usaha.",
    reports: [
      {
        key: "accounts-payable-aging",
        path: "/erp/reports/accounts-payable-aging",
        title: "Accounts Payable Aging",
        description: "Hutang usaha per supplier berdasarkan umur hutang.",
        purpose: "Untuk monitoring hutang yang jatuh tempo.",
        ideas: ["Aging 0-30, 31-60, 61-90, 90+", "Outstanding per supplier", "Monitoring jatuh tempo"],
      },
      {
        key: "cash-reconciliation",
        path: "/erp/reports/cash-reconciliation",
        title: "Cash Reconciliation",
        description: "Rekonsiliasi kas per shift — opening → sales → expenses → withdrawals → expected → actual.",
        purpose: "Untuk mendeteksi selisih kas per shift.",
        ideas: ["Opening vs expected vs actual", "Cash sales breakdown", "Variance detection"],
      },
    ],
  },
];

export const ERP_REPORTS = REPORT_GROUPS.flatMap((group) =>
  group.reports.map((report) => ({
    ...report,
    groupKey: group.key,
    groupTitle: group.title,
  }))
);
