const PERMISSION_MODULES = [
  {
    code: "overview",
    name: "Overview",
    description: "Ringkasan dashboard dan insight utama ERP.",
    sortOrder: 1,
    permissions: [
      {
        code: "reports:read",
        name: "View ERP dashboard",
        description: "Melihat ringkasan dashboard dan laporan utama ERP.",
        action: "read",
        sortOrder: 1,
      },
      {
        code: "erp:navigation:read",
        name: "View ERP navigation",
        description: "Melihat struktur sidebar ERP sesuai permission.",
        action: "read",
        sortOrder: 2,
      },
      {
        code: "erp:attendance:read",
        name: "View ERP attendance overview",
        description: "Melihat ringkasan absensi dari sisi ERP.",
        action: "read",
        sortOrder: 3,
      },
      {
        code: "erp:performance:read",
        name: "View ERP performance overview",
        description: "Melihat ringkasan performa crew dari sisi ERP.",
        action: "read",
        sortOrder: 4,
      },
      {
        code: "erp:cash-sessions:read",
        name: "View ERP cash sessions overview",
        description: "Melihat ringkasan sesi kas dari sisi ERP.",
        action: "read",
        sortOrder: 5,
      },
    ],
  },
  {
    code: "branch-ops",
    name: "Branch Operations",
    description: "Pengelolaan cabang dan assignment operasional.",
    sortOrder: 2,
    permissions: [
      { code: "branches:read", name: "View branches", description: "Lihat daftar branch.", action: "read", sortOrder: 1 },
      { code: "branches:write", name: "Manage branches", description: "CRUD branch.", action: "write", sortOrder: 2 },
      { code: "branch-assignments:read", name: "View branch assignments", description: "Lihat assignment kru.", action: "read", sortOrder: 3 },
      { code: "branch-assignments:write", name: "Manage branch assignments", description: "Ubah assignment kru.", action: "write", sortOrder: 4 },
    ],
  },
  {
    code: "sales-pos",
    name: "POS & Sales",
    description: "Transaksi, void, dan ringkasan penjualan.",
    sortOrder: 3,
    permissions: [
      { code: "transactions:read", name: "View transactions", description: "Lihat riwayat transaksi.", action: "read", sortOrder: 1 },
      { code: "transactions:write", name: "Manage transactions", description: "Buat transaksi dan void sesuai izin.", action: "write", sortOrder: 2 },
      { code: "cash-sessions:read", name: "View cash sessions", description: "Lihat sesi kasir.", action: "read", sortOrder: 3 },
      { code: "cash-sessions:write", name: "Manage cash sessions", description: "Open/close shift.", action: "write", sortOrder: 4 },
    ],
  },
  {
    code: "cash-withdrawals",
    name: "Cash Withdrawals",
    description: "Setoran cash outlet dengan OTP dari owner.",
    sortOrder: 3.5,
    permissions: [
      { code: "cash-withdrawals:read", name: "View cash withdrawals", description: "Lihat daftar setoran cash outlet.", action: "read", sortOrder: 1 },
      { code: "cash-withdrawals:write", name: "Request cash withdrawal", description: "Ajukan setoran cash outlet dan verifikasi OTP.", action: "write", sortOrder: 2 },
      { code: "cash-withdrawals:issue", name: "Issue withdrawal OTP", description: "Buat dan bagikan OTP setoran cash.", action: "issue", sortOrder: 3 },
    ],
  },
  {
    code: "inventory",
    name: "Inventory",
    description: "Master item, stok branch, opname, dan movement.",
    sortOrder: 4,
    permissions: [
      { code: "inventory:read", name: "View inventory", description: "Lihat item dan stok.", action: "read", sortOrder: 1 },
      { code: "inventory:write", name: "Manage inventory", description: "CRUD item dan stok.", action: "write", sortOrder: 2 },
      {
        code: "inventory:stock-opname:write",
        name: "Complete stock opname",
        description: "Simpan hasil opening atau closing stock opname.",
        action: "write",
        sortOrder: 3,
      },
    ],
  },
  {
    code: "depot-transfers",
    name: "Depot Transfers",
    description: "Transfer stok dari depo ke outlet dan approval cashier.",
    sortOrder: 4.5,
    permissions: [
      { code: "depot-transfers:read", name: "View depot transfers", description: "Lihat daftar transfer depo.", action: "read", sortOrder: 1 },
      { code: "depot-transfers:write", name: "Manage depot transfers", description: "Buat dan ubah transfer depo.", action: "write", sortOrder: 2 },
      { code: "depot-transfers:approve", name: "Approve depot transfers", description: "Approve transfer oleh cashier shift aktif.", action: "approve", sortOrder: 3 },
    ],
  },
  {
    code: "menu-recipe",
    name: "Menu & Recipe",
    description: "Produk, kategori, branch pricing, dan resep.",
    sortOrder: 5,
    permissions: [
      { code: "products:read", name: "View products", description: "Lihat master produk.", action: "read", sortOrder: 1 },
      { code: "products:write", name: "Manage products", description: "CRUD produk.", action: "write", sortOrder: 2 },
      { code: "product-categories:read", name: "View product categories", description: "Lihat kategori produk.", action: "read", sortOrder: 3 },
      { code: "product-categories:write", name: "Manage product categories", description: "CRUD kategori produk.", action: "write", sortOrder: 4 },
      { code: "branch-products:read", name: "View branch products", description: "Lihat harga per branch.", action: "read", sortOrder: 5 },
      { code: "branch-products:write", name: "Manage branch products", description: "Ubah harga/availability per branch.", action: "write", sortOrder: 6 },
    ],
  },
  {
    code: "purchasing",
    name: "Purchasing & Expenses",
    description: "Supplier, purchase request, purchase order, goods receipt, dan outlet expense.",
    sortOrder: 6,
    permissions: [
      { code: "purchasing:read", name: "View purchasing", description: "Lihat expense dan purchasing.", action: "read", sortOrder: 1 },
      { code: "purchasing:write", name: "Manage purchasing", description: "CRUD outlet expense dan pembelian.", action: "write", sortOrder: 2 },
      { code: "suppliers:read", name: "View suppliers", description: "Lihat data supplier.", action: "read", sortOrder: 3 },
      { code: "suppliers:write", name: "Manage suppliers", description: "CRUD supplier.", action: "write", sortOrder: 4 },
      { code: "purchasing-request:read", name: "View purchase requests", description: "Lihat PR.", action: "read", sortOrder: 5 },
      { code: "purchasing-request:write", name: "Manage purchase requests", description: "CRUD dan approve PR.", action: "write", sortOrder: 6 },
      { code: "purchasing-order:read", name: "View purchase orders", description: "Lihat PO.", action: "read", sortOrder: 7 },
      { code: "purchasing-order:write", name: "Manage purchase orders", description: "CRUD dan approve PO.", action: "write", sortOrder: 8 },
      { code: "goods-receipt:read", name: "View goods receipts", description: "Lihat penerimaan barang.", action: "read", sortOrder: 9 },
      { code: "goods-receipt:write", name: "Manage goods receipts", description: "Buat penerimaan barang.", action: "write", sortOrder: 10 },
    ],
  },
  {
    code: "crew",
    name: "Crew & Attendance",
    description: "User, role assignment, attendance, dan performa crew.",
    sortOrder: 7,
    permissions: [
      { code: "users:read", name: "View users", description: "Lihat user.", action: "read", sortOrder: 1 },
      { code: "users:write", name: "Manage users", description: "CRUD user.", action: "write", sortOrder: 2 },
    ],
  },
  {
    code: "reports",
    name: "Reports",
    description: "Laporan operasional dan performa.",
    sortOrder: 8,
    permissions: [
      { code: "reports:read", name: "View reports", description: "Akses laporan dan dashboard.", action: "read", sortOrder: 1 },
    ],
  },
  {
    code: "returns",
    name: "Returns & Waste",
    description: "Return pembelian dan waste management.",
    sortOrder: 6.5,
    permissions: [
      { code: "returns:read", name: "View returns", description: "Lihat return pembelian.", action: "read", sortOrder: 1 },
      { code: "returns:write", name: "Manage returns", description: "CRUD return pembelian.", action: "write", sortOrder: 2 },
      { code: "waste:read", name: "View waste", description: "Lihat waste management.", action: "read", sortOrder: 3 },
      { code: "waste:write", name: "Manage waste", description: "Catat waste barang.", action: "write", sortOrder: 4 },
    ],
  },
  {
    code: "master-data",
    name: "Master Data",
    description: "Referensi sistem yang dipakai lintas modul.",
    sortOrder: 9,
    permissions: [
      { code: "master-data:read", name: "View master data", description: "Lihat referensi sistem.", action: "read", sortOrder: 1 },
      { code: "master-data:write", name: "Manage master data", description: "Ubah referensi sistem.", action: "write", sortOrder: 2 },
    ],
  },
  {
    code: "payroll",
    name: "Payroll",
    description: "Gaji crew, bonus, dan potongan.",
    sortOrder: 7.5,
    permissions: [
      { code: "payroll:read", name: "View payroll", description: "Lihat payroll.", action: "read", sortOrder: 1 },
      { code: "payroll:write", name: "Manage payroll", description: "CRUD payroll.", action: "write", sortOrder: 2 },
    ],
  },
  {
    code: "settings",
    name: "Settings & System",
    description: "Konfigurasi sistem, feature flags, dan audit log.",
    sortOrder: 10,
    permissions: [
      { code: "settings:read", name: "View settings", description: "Lihat system settings.", action: "read", sortOrder: 1 },
      { code: "settings:write", name: "Manage settings", description: "Ubah system settings.", action: "write", sortOrder: 2 },
      { code: "audit-logs:read", name: "View audit logs", description: "Lihat log aktivitas.", action: "read", sortOrder: 3 },
    ],
  },
  {
    code: "access-control",
    name: "Access Control",
    description: "Manajemen role, permission, dan matrix akses.",
    sortOrder: 11,
    permissions: [
      { code: "access-control:read", name: "View access control", description: "Lihat matrix role-permission.", action: "read", sortOrder: 1 },
      { code: "access-control:write", name: "Manage access control", description: "Ubah hak akses tiap role.", action: "write", sortOrder: 2 },
    ],
  },
];

const DEFAULT_ROLES = [
  {
    code: "SUPERADMIN",
    name: "Super Admin",
    description: "Akses penuh ke semua modul ERP.",
    branchScope: "ALL",
    isSystem: true,
  },
  {
    code: "OWNER",
    name: "ERP Admin",
    description: "Akses operasional dan laporan lengkap.",
    branchScope: "ALL",
    isSystem: true,
  },
  {
    code: "ADMIN",
    name: "Admin",
    description: "Operasional cabang terbatas sesuai izin.",
    branchScope: "ALL",
    isSystem: true,
  },
  {
    code: "PURCHASING",
    name: "Purchasing",
    description: "Fokus pembelian, inventory, dan expense.",
    branchScope: "SINGLE",
    isSystem: true,
  },
  {
    code: "CREW",
    name: "Outlet Crew",
    description: "Akses crew untuk POS, attendance, dan stok opname.",
    branchScope: "SINGLE",
    isSystem: true,
  },
];

const DEFAULT_ROLE_PERMISSION_CODES = {
  SUPERADMIN: ["*"],
  OWNER: ["*"],
  ADMIN: [
    "erp:navigation:read",
    "reports:read",
    "erp:attendance:read",
    "erp:performance:read",
    "erp:cash-sessions:read",
    "branches:read",
    "branches:write",
    "branch-assignments:read",
    "branch-assignments:write",
    "transactions:read",
    "transactions:write",
    "cash-sessions:read",
    "cash-sessions:write",
    "cash-withdrawals:read",
    "cash-withdrawals:write",
    "cash-withdrawals:issue",
    "inventory:read",
    "inventory:write",
    "inventory:stock-opname:write",
    "depot-transfers:read",
    "depot-transfers:write",
    "depot-transfers:approve",
    "products:read",
    "products:write",
    "product-categories:read",
    "product-categories:write",
    "branch-products:read",
    "branch-products:write",
    "purchasing:read",
    "purchasing:write",
    "suppliers:read",
    "suppliers:write",
    "purchasing-request:read",
    "purchasing-request:write",
    "purchasing-order:read",
    "purchasing-order:write",
    "goods-receipt:read",
    "goods-receipt:write",
    "returns:read",
    "returns:write",
    "waste:read",
    "waste:write",
    "payroll:read",
    "payroll:write",
    "users:read",
    "users:write",
    "master-data:read",
    "master-data:write",
    "settings:read",
    "audit-logs:read",
  ],
  PURCHASING: [
    "erp:navigation:read",
    "reports:read",
    "inventory:read",
    "inventory:write",
    "depot-transfers:read",
    "depot-transfers:write",
    "purchasing:read",
    "purchasing:write",
    "suppliers:read",
    "suppliers:write",
    "purchasing-request:read",
    "purchasing-request:write",
    "purchasing-order:read",
    "purchasing-order:write",
    "goods-receipt:read",
    "goods-receipt:write",
    "returns:read",
    "returns:write",
    "master-data:read",
    "settings:read",
  ],
  CREW: [
    "erp:navigation:read",
    "reports:read",
    "transactions:read",
    "transactions:write",
    "cash-sessions:read",
    "cash-sessions:write",
    "cash-withdrawals:read",
    "cash-withdrawals:write",
    "inventory:read",
    "inventory:stock-opname:write",
    "depot-transfers:read",
    "depot-transfers:approve",
    "returns:read",
    "returns:write",
    "waste:read",
    "waste:write",
    "purchasing:read",
    "purchasing:write",
  ],
};

module.exports = {
  PERMISSION_MODULES,
  DEFAULT_ROLES,
  DEFAULT_ROLE_PERMISSION_CODES,
};
